"""empty message

Revision ID: f02f8b3fefd1
Revises: 9a107809ba2d
Create Date: 2026-01-14 22:13:29.701887

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f02f8b3fefd1"
down_revision: Union[str, None] = "9a107809ba2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    # ### end Alembic commands ###
